apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: fastapi-vs
  namespace: production
spec:
  host: fastapi.lab.local
  ingressClassName: nginx
  tls:
    secret: fastapi-lab-tls
    redirect:
      enable: true
      code: 301
  policies:
  - name: rate-limit-standard
  upstreams: []
  routes:
  - path: /items
    route: production/items-route
  - path: /
    route: production/gateway-route

