apiVersion: v1
kind: Service
metadata:
  name: items-service-v2
  namespace: production
  labels:
    app: items-service-v2
    version: "2.0.0"
spec:
  type: ClusterIP
  selector:
    app: items-service-v2
  ports:
  - name: http
    port: 80
    targetPort: 80
