apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-dev
  namespace: argocd
  labels:
    environment: dev
    team: platform
spec:
  project: default
  source:
    repoURL: https://github.com/Jeremieon/k3s-lab.git
    targetRevision: main
    path: fastapi-chart
    helm:
      valueFiles:
        - ../helm-values/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
