global:
  environment: production
itemsService:
  replicaCount: 2
  image:
    tag: "20260321-231358-b2550d7"
  config:
    LOG_LEVEL: "info"
gatewayService:
  replicaCount: 2
  image:
    tag: "20260321-232900-81d2e6f"
  config:
    LOG_LEVEL: "info"
    TIMEOUT_SECONDS: "5"
