global:
  environment: production

itemsService:
  replicaCount: 2
  image:
    tag: "2.0.2"
  config:
    LOG_LEVEL: "info"

gatewayService:
  replicaCount: 2
  image:
    tag: "1.0.1"
  config:
    LOG_LEVEL: "info"
    TIMEOUT_SECONDS: "5"
