global:
  environment: dev
itemsService:
  replicaCount: 1
  image:
    tag: "20260321-221338-0a2e244"
  config:
    LOG_LEVEL: "debug"
gatewayService:
  replicaCount: 1
  image:
    tag: "1.0.0"
  config:
    LOG_LEVEL: "debug"
    TIMEOUT_SECONDS: "10"
